### PR TITLE
A bunch of features

### PR DESCRIPTION
**Pull request by wyhasany**
I've made overlook on all forks. I've merged all features at my branch.
It would be really cool to merge them into main repository branch.

Changelog:
1. Export photos from README to relative path
2. Update README description
3. Check if pidfile is not empty
4. Check if process runs after its execution
5. Make script working offline
6. Script can handle parameters
7. Fix name/service_name misunderstending

### CODE REVIEW

**Comment by jasonblewis** [comment]
Hi wyhasany,

I've merged this. I'm no longer able to maintain this project. Would you like to become the maintainer? I can transfer the project to you on github.

https://help.github.com/articles/about-repository-transfers/

let me know?

**Comment by wyhasany** [comment]
Yeah, I would like to maintain it!

**Comment by jasonblewis** [comment]
in order for me to transfer it to you, I think you must remove your fork . Check the instructions. Once you've done that I'll transfer it to you

**Comment by wyhasany** [comment]
I've deleted my fork so you can transfer repository to me.

**Comment by jasonblewis** [comment]
transfer initiated

**Pull request merged**
